#!/bin/sh
lb clean noauto "$@"
rm -f -r config/binary config/bootstrap \
      config/chroot config/common config/source \
      config/package-lists/live.list.chroot \
      config/packages.chroot/* \
      config/includes.chroot/* \
      config/includes.installer/*
find config/hooks/ -type l | xargs --no-run-if-empty rm -f
